### ISSUE TITLE
Clarify [oas-types] rule: UpperCamelCase for all components

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#163]
Extend naming guidelines for data types [oas-types] (below) to cover all definitions of components (responses, requestBodies, ...)

> Rule: Naming of data types [[oas-types]](https://www.belgif.be/specification/rest/api-guide/#rule-oas-types)
> Data type names SHOULD be defined in American English and use UpperCamelCase notation. For abbreviations as well, all letters except the first one should be lowercased.
> 
> Do not use underscores (_), hyphens (-) or dots (.) in a data type name, nor use a digit as first letter.
> 
> Overly generic terms like info(rmation) and data SHOULD NOT be used as data type name or part of it.

**Comment by pvdbosch** [comment]
WG is OK to update the rule, I'll work out PR.

**Comment by pvdbosch** [comment]
PR #172 ready for review

**Comment by jpraet** [comment]
So this also applies to securitySchemes, right?

We currently have this:

```
components:
  securitySchemes:
    oauth-socsec:
      type: oauth2
      description: access using access token retrieved from oauth2 server
      flows:
        clientCredentials:
          tokenUrl: https://placeholder.socialsecurity.be/oauth2endpoint
          scopes:
            "scope:cbss:api:foreignLegalEntity:consult": consult foreign legal entities
            "scope:cbss:api:monitoring": access to health check operation
security:
  - oauth-socsec:
      - scope:cbss:api:foreignLegalEntity:consult
      - scope:cbss:api:monitoring
```
