### ISSUE TITLE
Update GitHub actions

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#170]
In builds of rest-guide and the openapi-* projects, we have some deprecation warnings in the builds about

* https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/   => will be problem in Spring 2024
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

For rest-guide, I already updated two offending github actions to latest version (+ JDK 17):
```YAML
    - uses: actions/checkout@v4
    - name: Set up Adopt OpenJDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: '17'
```

The release actions (actions/create-release@v1 and actions/upload-release-asset@v1) have become unmaintained however, and should be replaced by alternatives.

Is there someone who wants to work on this?
