### ISSUE TITLE
Response type for "/doc/openapi.yaml"

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#175]
When documenting the "GET /doc/openapi.yaml" operation in OpenAPI, as in [[doc-refdata]](https://www.belgif.be/specification/rest/api-guide/#rule-doc-refdata), max compatibility with tooling is achieved when specifying the payload as binary:

```YAML
    OpenApiResponse:
      description: OpenAPI document describing this API
      content:
        application/yaml:
          schema:
            type: string
            format: binary
```

Non-binary payload `type: object` has undefined behavior for YAML content-type. Binary format is also the only one allowed currently by the validator.

Can we document this payload format in the guide and add it to openapi-common? I often see problems with it in OpenAPIs (wrong media type or other schema).

Also, we could modify the [[doc-refdata]](https://www.belgif.be/specification/rest/api-guide/#rule-doc-refdata) rule to prefer publishing as YAML (SHOULD) over JSON (OPTIONAL), conform to [[oas-yaml]](https://www.belgif.be/specification/rest/api-guide/#rule-oas-yaml).
