### ISSUE TITLE
Allow some use of 'title' in schemas

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#176]
Current rule: https://www.belgif.be/specification/rest/api-guide/#rule-oas-descr

>  The title property MUST NOT be used because it hides the actual data type name in visualization tools like Swagger UI.

However, title property is useful in two cases:
* for inline schemas, to override the generated class name (e.g. openapi-generator). Currently, inline schemas are often moved to top-level schemas under `components` bc of this, even though they're not really reusable.
* redocly viewer sometimes messes up, showing the name of a parent schema inside 'oneOf'/'anyOf'

So I propose to change this to:

For schemas defined under `components`, the `title` property MUST NOT override the name of the schema because it would hide the actual schema name in visualization tools like Swagger UI.

**Comment by pvdbosch** [comment]
Some tests:
* title is used for display in SwaggerUI, also for inline schemas:
<img width="2452" height="669" alt="Image" src="https://github.com/user-attachments/assets/e6a1d04a-259d-4792-9705-a7ff407771b6" />

* for codegen of a schema component, title doesn't override the component name 
* for codegen of an inline schema, title is used. Otherwise, a class name is generated that can be very long

```YAML
components:
  schemas:
    ReusableSchema:
      title: WithAnotherSchemaName
      type: object
      properties:
        inlineSchemaWithoutTitle:
          type: object
          # without title: generates class "ReusableSchemaInlineSchemaWithoutTitle"
          # add  title: InlineSchema    to generate InlineSchema as class name
          properties:
            propertyOfInlineSchema:
              type: string
```
