### ISSUE TITLE
Recommended use of discriminator, oneOf, inheritance

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#181]
We're regularly encountering errors when oneOf or discriminators are being used.

* OpenAPI document authors sometimes mistakenly assume that the oneOf subschema types are part of the JSON message; and that it can easily be retrieved as a data element by applications interacting with the API.
* oneOf with object-type subschemas and discriminator property should work
  * this generates inheritance with type info annotations to deserialization can be done to the correct generated child class
  *  we may recommend always use "mapping", and against serializing the schema names (they're also not lowerCamelCase so invalid wrt [_cod-design]_
    * for "any-type" lists, like "embedded", this could become difficult though
* oneOf with object-type subschemas without a discriminator might not be deserializable 
  * it's missing type info annotations needed to determine child class, but to be tested if inherited classes actually get generated in this case
* oneOf with simple, non-object types, probably leads to problems (TBC)
* oneOf with subschemas that only define "required" properties can be a good alternative, like used for [BelgianRemittanceInformation](https://github.com/belgif/openapi-money/blob/master/src/main/openapi/money/v1/money-v1.yaml#L71)
  * this generates a flat class structure. The allowed combinations of properties isn't visible in generated classes, but can still be validated if validating the exchanged messages against the schema in the OpenAPI document

**Comment by pvdbosch** [comment]
Confirmed that oneOf with simple types gives bad code generation results, for instance:    

```YAML
  BelgianRemittanceInformationOneOfTwoStrings:
      oneOf:
        - description: Unstructured Remittance Information as supported by Belgian banks
          type: string
          maxLength: 140
        - description: Structured Remittance Information in the Belgian OGM-VCS format. Often formatted for display as +++ 3 digits / 4 digits / 5 digits / +++.
          type: string
          pattern: "^\\d{12}$"
          example: "010806817183"
```

generates:
```Java
public interface BelgianRemittanceInformationOneOfTwoStrings {
}
```
without any subclasses of this empty interface.
Tested using openapi-generator 7.5.0, same behavior when using referenced subschemas instead of inline ones.
