### ISSUE TITLE
OpenAPI 3 : parameter serialization modes

### ISSUE THREAD

**Issue by wsalembi** [belgif/rest-guide#56]
OpenAPI 3 adds multiple options to serialize JSON (primitive, array, object) in header, query parameters. Which ones do we want to follow?

https://swagger.io/docs/specification/serialization/

**Comment by pvdbosch** [comment]
I guess "explode: true" shouldn't be used with spaceDelimited and pipeDelimited. 
"OpenAPI spec":https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#style-examples doesn't specify this, only the swagger doc but doesn't make much sense.

**Comment by pvdbosch** [comment]
My proposition...

For query params:
* use defaults (style: form, exploded: true). 
  * This is compatible with our current guidelines for primitive values and arrays/multi-valued.
* perhaps recommend against using object types?
  * seems like a pain for tooling (probably don't support this form of (de)serialization) and is complex to interpret for users
  * for use cases at CBSS where querying has to be done on nested properties of the resource representation, we use individiual dot-separated query param names like "?address.street=X&address.country=Y"

For headers,  in the spec style has to be simple. explode param only has an effect for object values, but I don't really see a use case and could be a pain for tooling.

For path params: simple (default normal formatting) and recommend only primitive objects (so explode has no effect) since path params are normally used as a resource id:
  * If a resource is identified by multiple values, these should be in separate path segments (e.g. /blogs/5/comments/23). 
  * If there's a composite id for technical reasons (e.g. /images/database1-image1/), this should be presented as an abstraction to a  single primitive value in the API for the user

**Comment by pvdbosch** [comment]
A feature of OpenAPI I hadn't noticed yet before: it also supports specifying a parameter using a media type:

* https://swagger.io/docs/specification/describing-parameters/
* https://spec.openapis.org/oas/v3.1.0#parameter-object

```YAML
parameters:
  - in: query
    name: select
    content: # instead of schema property
      application/json:  # only single media type entry allowed; indicates how to (de)serialize (but algorithm not specified in OAS)
        schema:
          type: object
          properties:
            givenName
              type: string
            familyName:
              type: string
```

Haven't used it yet, so don't know how well this is supported in tooling
