### ISSUE TITLE
integer vs. string for numerical codes and identifiers

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#60]
During discussion of the representation of EmployerId (= nsso number + variants), the question surfaced if it shouldn't be represented by an integer instead of a string because in (human) input, the leading zeros are often omitted. The same could be said for EnterpriseNumber, where the first digit can be omitted if it is zero (the format doesn't permit two leading zeros).

One could also represent this as a string with a regular expression, but this may lead to programming bugs when comparing values:
* "880813349" != "0880813349"  (string comparison) => NOK
* 880813349 == 0880813349 (number comparison) => OK

We currently have this rule ; it would need to be tweaked to allow this:

> When defining the type for a property representing a numerical code or identifier:
> 
> if the values constitute a list of sequentially generated codes (e.g. gender ISO code), type: integer SHOULD be used. It is RECOMMENDED to further restrict the format of the type (e.g. format: int32).
> 
> if the values are of fixed length or not sequentially generated, type: string SHOULD be used (e.g. Ssin, EnterpriseNumber). This avoids leading zeros to be hidden.
> 
> When using a string data type, each code SHOULD have a unique representation, e.g. don’t allow representations both with and without a leading zeros or spaces for a single code. If possible, specify a pattern with a regular expression restricting the allowed representations.

a) as string:
```
  EmployerId:
    description: Definitive or provisional NSSO number, assigned to each registered employer or local or provincial administration.
    type: string
    pattern: '^5?\d{9}$' # first digit 5 indicates a provisional NSSO number
    example: '000100006'

  EnterpriseNumber:
    description: Identifier issued by CBE for a registered organization
    type: string
    pattern: '^[0|1]\d{9}$'
```

b) as integer:
```
  EmployerId:
    description: Definitive or provisional NSSO number, assigned to each registered employer or local or provincial administration.
    type: integer
    minimum: 0
    maximum: 5999999999
    example: 197
   #this allows some invalid values like 10 digits starting with 4

  EnterpriseNumber:
    description: Identifier issued by CBE for a registered organization
    type: integer
    minimum: 100000000
    maximum: 1999999999
    example: 880813349
```

(similar for EstablishmentUnitNumber and CbeNumber)

For Ssin, string representation should still be kept, because its fixed length and leading zeros have a meaning (year of birth).
