### ISSUE TITLE
indicate one of a list of scopes are required [problems/missingScope]

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#72]
An API designer can allow access (specified in OpenAPI) to an operation if:
* all of multiple scopes is present in JWT 
* one of multiple scopes is present
* any combination of the above

The missingScope problem type only allows for the first case:  "The requiredScopes property lists the required scopes."
Can we extend the problem type structure to also allow for the other cases?

OpenAPI even allows security requirements listing a mix of mechanisms, e.g.:

```
"security": [
 { "oauth-authorizationCode": ["scope1"] },
 { "oauth-authorizationCode": ["scope2"], "httpBasicAuth": "" },
 { "oauth-clientCredentials": ["scope2"], "mutualTLSAuth": "" }
]
```
note: mutualTLS will be supported only in OAS3.1.

**Comment by jpraet** [comment]
Related to this:

According to the spec, logical "AND" and "OR" for scopes can be expressed as follows

```yaml
# User needs scopes A AND B
security:
  - oauth2:
    - A
    - B

# User needs scope A OR B
security:
  - oauth2:
    - A
  - oauth2:
    - B

# User needs scope (A AND B) OR C
security:
  - oauth2:
    - A
    - B
  - oauth2:
    - C
```

But the Smals API Deployer tool fails on this:

```yaml
# User needs scope A OR B
security:
  - oauth2:
    - A
  - oauth2:
    - B
```

With exception "java.lang.IllegalArgumentException: For operation getCard the scopes in each security requirements must be equal"

Instead, we need to configure a custom vendor-specific extension:

```yaml
# User needs scope A OR B
security:
  - oauth2:
    - A
    - B
x-oauth2-required-scopes: any
```
