### ISSUE TITLE
representation of decimal numbers

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#79]
How to represent decimal numbers with fixed precision: as number or as string type?

For use in MonetaryAmount, see https://github.com/belgif/openapi-money/issues/2 

For decimals with fixed precision:
* floating point numbers aren't advisable for money, because of [calculation errors](https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html)
* in the wild, we encounter "type: number with format: decimal" ([Zalando](https://opensource.zalando.com/restful-api-guidelines/#171)) and "type: string with format: number" (openapi-generator) for precise decimal numbers (BigDecimal etc.)
  * There's some talk about this in JSON Schema list: https://github.com/json-schema-org/json-schema-spec/issues/361
* limiting min/max is difficult when reusing an existing (string) type. Do we provide two types: allowing pos+neg and allowing only non-negative?

So two options:

A) use number type with format, not in openapi-common

```yaml
MoneyAmount:
  type: number
  format: decimal 
```

=> might be converted to float by default which is dangerous (can someone test?)

variant: add "multipleOf: 0.0001" to express precision. But this can also lead to other floating point problems for libraries implementing this (https://github.com/json-schema-org/json-schema-spec/issues/312 , https://github.com/xeipuuv/gojsonschema/issues/149).

 
B) define Decimal type based on string

```yaml
  Decimal:
      type: string
      format: decimal # decimal is a custom format only supported in some tooling
      pattern: '^(\-|\+)?((\d+(\.\d*)?)|(\.\d+))$'  # based on BigDecimal (Java) but without exponent support. At least one digit required, before or after comma
      # valid values:  "100.234567", "010", "-.05", "+1", "10", "100." 
  UnsignedDecimal:
      type: string
      format: decimal # decimal is a custom format only supported in some tooling
      pattern: '^((\d+(\.\d*)?)|(\.\d+))$'  
      # valid values:  "100.234567", "010", "10", "100." but not "+1", "-1"
```
=> has to be converted in code from string to appropriate decimal type (e.g. BigDecimal in Java)
