### ISSUE TITLE
Naming of properties and types for codes

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-guide#94]
When interpreting the current guidelines strictly, code porperties and types should be named "id".
This seems to be weird for readers, as "code" is more meaningful in these cases.  Should we allow "code" in the naming convention as well?

Example:
```YAML
    CivilStateId:
      description: The civil state of a person, represented by a code assigned by the National Register
      type: integer
      minimum: 1
      maximum: 99
```
```JSON
"civilState": {
   "id": 3,
   "description": "married"
}
```

This naming follows from the naming convention of identifiers, and that codes are a special type of identifiers.

```
"The identifier should be named `id` unless there already exists another standardized name for the business identifier."

In a JSON representation, it SHOULD NOT be prefixed unless the identifier is not of the resource on which the operation applies and there’s ambiguity.

If the identifier is used as path parameter, it should be prefixed by the resource type.
```

```
A code is a special type of identifier:
* it has an exhaustive list of possible values that doesn’t change frequently over time
* each value identifies a concept (examples: a country, a gender, …​).
```

**Comment by pvdbosch** [comment]
WG is OK with proposed change, I'll work on a PR.

**Comment by pvdbosch** [comment]
Discussion was reopened.

To recap:

Goal: naming guidelines for properties and types for codes

Semantic standards (RDF, Skos etc):
* a ConceptScheme is a scheme that defines how to represent a certain property
  * ~ to a code list for a property
* a Concept defines the meaning of a single value (code). It defines both to the unique technical representation (URI, code) as its description (label in different languages)

There may be multiple alternative ConceptSchemes for a single property e.g. NIS code and an ISO alpha2/alpha3/num3 for a country

Examples:

pseudo-rdf:
```
<country> is a property of <Address>
<CountryIsoAlpha2> is a ConceptScheme
<BE> is a Concept
<BE> is part of scheme <CountryIsoAlpha2>
```

REST/OpenAPI:
* a type defines a set of constraints that can be applied on a JSON value
* the representation of a concept in a JSON message is often done only with the code, but in other cases the description is also returned alongside it (e.g. to make it easier to represent in a UI)

Examples of possible JSON:

```JSON
"civilState": {
   "code": 3,
   "description": "married"
},

"civilState": 3
```

types: 

```YAML
CivilState:
  type: object
  properties:
      code: {$ref: CivilStateCode}
      description: { type: string}

CivilStateCode:
   type: integer
   minimum: 1
   maximum: 99
```
